hpc<-read.table("C:/Users/185384/Documents/Personal/Self Learning/R/BasePlot/household_power_consumption.txt", sep =";", header = TRUE, stringsAsFactors = FALSE)
str(hpc)
head(hpc,5)
library(dplyr)
library(lubridate)
names(hpc)
hpc<-mutate(hpc,Global_active_power= as.numeric(Global_active_power))
hpc <- mutate(hpc,Date = dmy(Date))
hpc <- filter(hpc,Date>= ymd("2007-02-01") & Date<= ymd("2007-02-03"))
hpc <- mutate(hpc,date_name = wday(Date, label = TRUE))
png(filename="C:/Users/185384/Documents/Personal/Self Learning/R/BasePlot/plot1.png")
hist(hpc$Global_active_power,xlab = "Global Active Power (kilowatts)", main = "Global Active Power", col = "red" )
dev.off()